@echo off
echo Démarrage de l'application Achat Revente...
echo.
echo Étape 1: Démarrage du serveur React...
start npm start
echo Serveur React en cours de démarrage...
echo.
echo Attente de 15 secondes pour que le serveur se prépare...
timeout /t 15 /nobreak
echo.
echo Étape 2: Lancement de l'application Electron...
start npm run electron
echo.
echo Application lancée! La fenêtre devrait s'afficher bientôt...
pause
